//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZOYI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115200")]
        public int baudrate {
            get {
                return ((int)(this["baudrate"]));
            }
            set {
                this["baudrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string default_com {
            get {
                return ((string)(this["default_com"]));
            }
            set {
                this["default_com"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pl")]
        public string lang {
            get {
                return ((string)(this["lang"]));
            }
            set {
                this["lang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string panel_std_label_color {
            get {
                return ((string)(this["panel_std_label_color"]));
            }
            set {
                this["panel_std_label_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string panel_std_value_color {
            get {
                return ((string)(this["panel_std_value_color"]));
            }
            set {
                this["panel_std_value_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string panel_std_bg_color {
            get {
                return ((string)(this["panel_std_bg_color"]));
            }
            set {
                this["panel_std_bg_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int main_form_pos_x {
            get {
                return ((int)(this["main_form_pos_x"]));
            }
            set {
                this["main_form_pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int main_form_pos_y {
            get {
                return ((int)(this["main_form_pos_y"]));
            }
            set {
                this["main_form_pos_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int panel_std_form_pos_x {
            get {
                return ((int)(this["panel_std_form_pos_x"]));
            }
            set {
                this["panel_std_form_pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int panel_std_form_pos_y {
            get {
                return ((int)(this["panel_std_form_pos_y"]));
            }
            set {
                this["panel_std_form_pos_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string panel_adv_label_color {
            get {
                return ((string)(this["panel_adv_label_color"]));
            }
            set {
                this["panel_adv_label_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string panel_adv_value_color {
            get {
                return ((string)(this["panel_adv_value_color"]));
            }
            set {
                this["panel_adv_value_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public string panel_adv_bar_color {
            get {
                return ((string)(this["panel_adv_bar_color"]));
            }
            set {
                this["panel_adv_bar_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string panel_adv_bg_color {
            get {
                return ((string)(this["panel_adv_bg_color"]));
            }
            set {
                this["panel_adv_bg_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int panel_adv_form_pos_x {
            get {
                return ((int)(this["panel_adv_form_pos_x"]));
            }
            set {
                this["panel_adv_form_pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int panel_adv_form_pos_y {
            get {
                return ((int)(this["panel_adv_form_pos_y"]));
            }
            set {
                this["panel_adv_form_pos_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int panel_adv_ticks {
            get {
                return ((int)(this["panel_adv_ticks"]));
            }
            set {
                this["panel_adv_ticks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int panel_adv_thicks_count {
            get {
                return ((int)(this["panel_adv_thicks_count"]));
            }
            set {
                this["panel_adv_thicks_count"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font panel_adv_label_font {
            get {
                return ((global::System.Drawing.Font)(this["panel_adv_label_font"]));
            }
            set {
                this["panel_adv_label_font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font panel_adv_value_font {
            get {
                return ((global::System.Drawing.Font)(this["panel_adv_value_font"]));
            }
            set {
                this["panel_adv_value_font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font panel_std_label_font {
            get {
                return ((global::System.Drawing.Font)(this["panel_std_label_font"]));
            }
            set {
                this["panel_std_label_font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font panel_std_value_font {
            get {
                return ((global::System.Drawing.Font)(this["panel_std_value_font"]));
            }
            set {
                this["panel_std_value_font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font panel_std_footer_font {
            get {
                return ((global::System.Drawing.Font)(this["panel_std_footer_font"]));
            }
            set {
                this["panel_std_footer_font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string panel_std_footer_color {
            get {
                return ((string)(this["panel_std_footer_color"]));
            }
            set {
                this["panel_std_footer_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int panel_opacity {
            get {
                return ((int)(this["panel_opacity"]));
            }
            set {
                this["panel_opacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool tts_enabled {
            get {
                return ((bool)(this["tts_enabled"]));
            }
            set {
                this["tts_enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tts_voice {
            get {
                return ((string)(this["tts_voice"]));
            }
            set {
                this["tts_voice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("112")]
        public int shortcut_ToggleStandardPanel {
            get {
                return ((int)(this["shortcut_ToggleStandardPanel"]));
            }
            set {
                this["shortcut_ToggleStandardPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("113")]
        public int shortcut_ToggleAdvancedPanel {
            get {
                return ((int)(this["shortcut_ToggleAdvancedPanel"]));
            }
            set {
                this["shortcut_ToggleAdvancedPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("114")]
        public int shortcut_ClearLog {
            get {
                return ((int)(this["shortcut_ClearLog"]));
            }
            set {
                this["shortcut_ClearLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115")]
        public int shortcut_SaveCSV {
            get {
                return ((int)(this["shortcut_SaveCSV"]));
            }
            set {
                this["shortcut_SaveCSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("116")]
        public int shortcut_ToggleChartPause {
            get {
                return ((int)(this["shortcut_ToggleChartPause"]));
            }
            set {
                this["shortcut_ToggleChartPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("117")]
        public int shortcut_ClearChart {
            get {
                return ((int)(this["shortcut_ClearChart"]));
            }
            set {
                this["shortcut_ClearChart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("118")]
        public int shortcut_MinimizeWindow {
            get {
                return ((int)(this["shortcut_MinimizeWindow"]));
            }
            set {
                this["shortcut_MinimizeWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("119")]
        public int shortcut_ToggleTTS {
            get {
                return ((int)(this["shortcut_ToggleTTS"]));
            }
            set {
                this["shortcut_ToggleTTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int shortcut_CycleTimeWindow {
            get {
                return ((int)(this["shortcut_CycleTimeWindow"]));
            }
            set {
                this["shortcut_CycleTimeWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123")]
        public int shortcut_OpenShortcutConfig {
            get {
                return ((int)(this["shortcut_OpenShortcutConfig"]));
            }
            set {
                this["shortcut_OpenShortcutConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Google")]
        public string ds_search_engine {
            get {
                return ((string)(this["ds_search_engine"]));
            }
            set {
                this["ds_search_engine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KRIS® VERSION")]
        public string panel_std_custom_name {
            get {
                return ((string)(this["panel_std_custom_name"]));
            }
            set {
                this["panel_std_custom_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GG 8772666")]
        public string panel_std_custom_gg {
            get {
                return ((string)(this["panel_std_custom_gg"]));
            }
            set {
                this["panel_std_custom_gg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ZOYI®        ZT-703S         OSCILLOSCOPE MULTIMETER")]
        public string panel_std_custom_title {
            get {
                return ((string)(this["panel_std_custom_title"]));
            }
            set {
                this["panel_std_custom_title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15.75")]
        public double panel_std_title_font_size {
            get {
                return ((double)(this["panel_std_title_font_size"]));
            }
            set {
                this["panel_std_title_font_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string skipped_version {
            get {
                return ((string)(this["skipped_version"]));
            }
            set {
                this["skipped_version"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font dq02_value_font {
            get {
                return ((global::System.Drawing.Font)(this["dq02_value_font"]));
            }
            set {
                this["dq02_value_font"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public string dq02_value_color {
            get {
                return ((string)(this["dq02_value_color"]));
            }
            set {
                this["dq02_value_color"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font dq02_prefix_font {
            get {
                return ((global::System.Drawing.Font)(this["dq02_prefix_font"]));
            }
            set {
                this["dq02_prefix_font"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public string dq02_prefix_color {
            get {
                return ((string)(this["dq02_prefix_color"]));
            }
            set {
                this["dq02_prefix_color"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font dq02_secondary_font {
            get {
                return ((global::System.Drawing.Font)(this["dq02_secondary_font"]));
            }
            set {
                this["dq02_secondary_font"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public string dq02_secondary_color {
            get {
                return ((string)(this["dq02_secondary_color"]));
            }
            set {
                this["dq02_secondary_color"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font panel_std_dq02_label_font {
            get {
                return ((global::System.Drawing.Font)(this["panel_std_dq02_label_font"]));
            }
            set {
                this["panel_std_dq02_label_font"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string panel_std_dq02_label_color {
            get {
                return ((string)(this["panel_std_dq02_label_color"]));
            }
            set {
                this["panel_std_dq02_label_color"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font dq02_passfail_font {
            get {
                return ((global::System.Drawing.Font)(this["dq02_passfail_font"]));
            }
            set {
                this["dq02_passfail_font"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string saved_control_positions {
            get {
                return ((string)(this["saved_control_positions"]));
            }
            set {
                this["saved_control_positions"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font lbl_status_font {
            get {
                return ((global::System.Drawing.Font)(this["lbl_status_font"]));
            }
            set {
                this["lbl_status_font"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font lbl_target_esr_font {
            get {
                return ((global::System.Drawing.Font)(this["lbl_target_esr_font"]));
            }
            set {
                this["lbl_target_esr_font"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool show_startup_warning {
            get {
                return ((bool)(this["show_startup_warning"]));
            }
            set {
                this["show_startup_warning"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5V")]
        public string riden_vset {
            get {
                return ((string)(this["riden_vset"]));
            }
            set {
                this["riden_vset"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1V")]
        public string riden_iset {
            get {
                return ((string)(this["riden_iset"]));
            }
            set {
                this["riden_iset"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string riden_ovp {
            get {
                return ((string)(this["riden_ovp"]));
            }
            set {
                this["riden_ovp"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font panel_std_riden_label_font {
            get {
                return ((global::System.Drawing.Font)(this["panel_std_riden_label_font"]));
            }
            set {
                this["panel_std_riden_label_font"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string panel_std_riden_label_color {
            get {
                return ((string)(this["panel_std_riden_label_color"]));
            }
            set {
                this["panel_std_riden_label_color"] = value;
            }
        }
    }
}
