//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZOYI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115200")]
        public int baudrate {
            get {
                return ((int)(this["baudrate"]));
            }
            set {
                this["baudrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string default_com {
            get {
                return ((string)(this["default_com"]));
            }
            set {
                this["default_com"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pl")]
        public string lang {
            get {
                return ((string)(this["lang"]));
            }
            set {
                this["lang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string panel_std_label_color {
            get {
                return ((string)(this["panel_std_label_color"]));
            }
            set {
                this["panel_std_label_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string panel_std_value_color {
            get {
                return ((string)(this["panel_std_value_color"]));
            }
            set {
                this["panel_std_value_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string panel_std_bg_color {
            get {
                return ((string)(this["panel_std_bg_color"]));
            }
            set {
                this["panel_std_bg_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int main_form_pos_x {
            get {
                return ((int)(this["main_form_pos_x"]));
            }
            set {
                this["main_form_pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int main_form_pos_y {
            get {
                return ((int)(this["main_form_pos_y"]));
            }
            set {
                this["main_form_pos_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int panel_std_form_pos_x {
            get {
                return ((int)(this["panel_std_form_pos_x"]));
            }
            set {
                this["panel_std_form_pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int panel_std_form_pos_y {
            get {
                return ((int)(this["panel_std_form_pos_y"]));
            }
            set {
                this["panel_std_form_pos_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string panel_adv_label_color {
            get {
                return ((string)(this["panel_adv_label_color"]));
            }
            set {
                this["panel_adv_label_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string panel_adv_value_color {
            get {
                return ((string)(this["panel_adv_value_color"]));
            }
            set {
                this["panel_adv_value_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string panel_adv_bg_color {
            get {
                return ((string)(this["panel_adv_bg_color"]));
            }
            set {
                this["panel_adv_bg_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int panel_adv_form_pos_x {
            get {
                return ((int)(this["panel_adv_form_pos_x"]));
            }
            set {
                this["panel_adv_form_pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int panel_adv_form_pos_y {
            get {
                return ((int)(this["panel_adv_form_pos_y"]));
            }
            set {
                this["panel_adv_form_pos_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int panel_adv_ticks {
            get {
                return ((int)(this["panel_adv_ticks"]));
            }
            set {
                this["panel_adv_ticks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int panel_adv_thicks_count {
            get {
                return ((int)(this["panel_adv_thicks_count"]));
            }
            set {
                this["panel_adv_thicks_count"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font panel_adv_label_font {
            get {
                return ((global::System.Drawing.Font)(this["panel_adv_label_font"]));
            }
            set {
                this["panel_adv_label_font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font panel_adv_value_font {
            get {
                return ((global::System.Drawing.Font)(this["panel_adv_value_font"]));
            }
            set {
                this["panel_adv_value_font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font panel_std_label_font {
            get {
                return ((global::System.Drawing.Font)(this["panel_std_label_font"]));
            }
            set {
                this["panel_std_label_font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font panel_std_value_font {
            get {
                return ((global::System.Drawing.Font)(this["panel_std_value_font"]));
            }
            set {
                this["panel_std_value_font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font panel_std_footer_font {
            get {
                return ((global::System.Drawing.Font)(this["panel_std_footer_font"]));
            }
            set {
                this["panel_std_footer_font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string panel_std_footer_color {
            get {
                return ((string)(this["panel_std_footer_color"]));
            }
            set {
                this["panel_std_footer_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int panel_opacity {
            get {
                return ((int)(this["panel_opacity"]));
            }
            set {
                this["panel_opacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool tts_enabled {
            get {
                return ((bool)(this["tts_enabled"]));
            }
            set {
                this["tts_enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tts_voice {
            get {
                return ((string)(this["tts_voice"]));
            }
            set {
                this["tts_voice"] = value;
            }
        }
    }
}
